= GLPI Container Architecture
A.C. <a dot costa at trikorasolutions dot com>
:Date:      {docdate}
:Revision:  1
:table-caption: Table
:toc: left
:toc-title: Table of Contents
:icons: font
:source-highlighter: rouge
:description: This document describes the container architecutre implemented 
on this project
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This section describes the architecture of the project.

== The containers

This project uses 3 GLPI containers that implement different tasks:

* `init` container
* `web` container
* `cron` container

=== init container

The init container is responsible for configuring, installing and upgrading the
GLPI instance. 

For the deployment preparation it defines 2 volumes that will presist the applied configuration:

* `/etc/glpi`: store the database configuration `config_db.php` as well 
as the `glpicrypt.key` file (link:https://glpi-install.readthedocs.io/en/develop/update.html[more information])
* `/var/lib/glpi`: stores link:https://glpi-install.readthedocs.io/en/latest/install/[GLPI data]

=== web container

The web container includes the GLPI runtime application. It startes the 
`apache` http server to serve the application.

This container must share the volumes with the init container so it inherits 
the GLPI configuration.

=== cron container

TBD
