= Deploy GLPI on a KinD cluster and local container registry
A. Costa <a dot costa at trikorasolutions dot com>
:description: This document describes the steps to deploy a new GLPI environment using KinD.
:icons: font
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the steps to deploy the a new GLPI environment using
link:https://kind.sigs.k8s.io/[KinD], a tool for running local Kubernetes clusters using Docker container “_nodes_” and a local container registry.

== Requirements

* link:https://kind.sigs.k8s.io/[KinD]
* Local installation of a container registry


[NOTE]
====
Installation script available on the link:https://github.com/snowdrop/k8s-infra/tree/main/kind[snowdrop/k8s-infra] GitHub project.
====

[NOTE]
====
Throughout the document it will be referred as `kind-registry.local`
====

== Push container images to local container registry

Get the latest references to the built images.

[source,bash]
----
$ buildah images
REPOSITORY                                          TAG                IMAGE ID       CREATED         SIZE
localhost/trikorasolns_glpi_web                     latest             a5754bf9974c   3 days ago      786 MB
localhost/trikorasolns_glpi_init                    latest             b2fff5bcb56a   3 days ago      786 MB
----

Push the container images to the local container registry.

[source,bash]
----
buildah push "localhost/trikorasolns_glpi_init:latest" docker://kind-registry.local:5000/trikorasolns_glpi_init:latest
buildah push "localhost/trikorasolns_glpi_web:latest" docker://kind-registry.local:5000/trikorasolns_glpi_web:latest
----

List the tagged images.

[source,bash]
----
curl -s http://localhost:5000/v2/trikorasolns_glpi_init/tags/list | jq .
----

[source,yaml]
----
{
  "name": "trikorasolns_glpi_init",
  "tags": [
    "latest"
  ]
}
----

[source,bash]
----
curl -s http://localhost:5000/v2/trikorasolns_glpi_web/tags/list | jq .
----

[source,yaml]
----
{
  "name": "trikorasolns_glpi_web",
  "tags": [
    "latest"
  ]
}
----

== Deploy the application

Prepare the host.

[source,bash]
----
ansible-playbook src/scripts/deploy/devKind/prepare-host.yaml -K
----

Deploy the KinD cluster.

[source,bash]
----
ansible-playbook src/scripts/deploy/devKind/deploy-kind-cluster.yaml
----

=== MariaDB

=== Init Container

=== Web Container

=== Cron Container
