= Deploy GLPI using Podman
A. Costa <a dot costa at trikorasolutions dot com>
:description: This document describes the steps to deploy a development environment using Podman.
:icons: font
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the steps to deploy the GLPI container image using
link:https://podman.io/[Podman] on a workstation (localhost).

== Requirements

* link:https://podman.io/[Podman]

Requires the container image to be built. Check link:build.adoc[The build document] for more information.

== Deploy the application

=== Locally on Podman

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-app.yaml
----

[NOTE]
====
Preparing the environment, create the POD and instanciate the database, can 
be accomplished by manually calling the `prepare-database.yaml` Ansible playbook.

The `prepare-glpi.yaml` creates the volumes and deploys te `init` container.
====

==== Manually deploy the containers

      containers.podman.podman_container:
        name: "{{ image_prefix }}_init"
        image: "localhost/{{ image_prefix }}"
        pod: "{{ pod_name }}"
        state: started
        command: /opt/glpi/glpi-install.sh
        env:
          GLPI_DB_HOST: "{{ image_prefix }}_db"
          GLPI_DB_PORT: 3306
          GLPI_DB_USER_NAME: "{{ mysql.user }}"
          GLPI_DB_USER_PASSWORD: "{{ mysql.password }}"
          GLPI_DB_NAME: "{{ mysql.database }}"
          # "pt_BR", "es_ES"
          GLPI_LANGUAGE: en_GB

[source,bash]
----
podman run --pod trikorasolns_glpi --name trikorasolns_glpi_init \
  -e GLPI_DB_HOST="trikorasolns_glpi_db" \
  -e GLPI_DB_PORT=3306 \
  -e GLPI_DB_USER_NAME="trikorasolns_glpi" \
  -e GLPI_DB_USER_PASSWORD="trikorasolns_glpi" \
  -e GLPI_DB_NAME="trikorasolns_glpi" \
  -e GLPI_LANGUAGE=en_GB \
  -v /tmp/glpi/var_lib:/var/lib/glpi:Z \
  -u 33:33 \
  localhost/trikorasolns_glpi /opt/glpi/glpi-install.sh
----


=== Access the application

Access the application through the following URL.

http://localhost:9380/glpi

Container console

[source,bash]
----
podman exec -it trikorasolns_glpi_glpi /bin/bash
----

== Undeploy the application

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/undeploy-app.yaml
----
