= Deploy GLPI using Podman
A. Costa <a dot costa at trikorasolutions dot com>
:description: This document describes the steps to deploy a new development environment using Podman.
:icons: font
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the steps to deploy the a new GLPI environment using
link:https://podman.io/[Podman].

== Requirements

* link:https://podman.io/[Podman]

Requires the container image to be built. Check link:build.adoc[The build document] for more information.


== Deploy the application

To deploy GLPI locally using Podman execute the ansible playbooks provided.

To deploy all components executing 1 command

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-app.yaml
----

== Deploy each component

=== Instanciate a MariaDB database

.Environment variables
[%header,cols="2,4"]
|===
| Variable | Description

| `mariadb_version`

[.fuchsia]#string# 

a| MariaDB database version.

_Default:_ `10.6`

| `image_prefix`

[.fuchsia]#string# 

a| Prefix applied to the container images.

_Default:_  `trikorasolns_glpi`

| `pod_name`

[.fuchsia]#string# 

a| Name to be given to the Podman POD

_Default:_ `trikorasolns_glpi`
|===


.mysql dictionary
[%header,cols="2,4"]
|===
| Variable | Description

| `mysql.database`

[.fuchsia]#string# 

a| Database name

_Default:_ `trikorasolns_glpi`

| `mysql.password`

[.fuchsia]#string# 

a| Database user password

_Default:_ `trikorasolns_glpi`

| `mysql.root_password`

[.fuchsia]#string# 

a| Database root password

_Default:_ `trikorasolns_glpi`

| `mysql.user`

[.fuchsia]#string# 

a| Database user

_Default:_ `trikorasolns_glpi`

|===

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-database.yaml
----

=== Deploy the init container

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-glpi-init.yaml
----

[NOTE]
====
To check the logs of the init container.

[source,bash]
----
podman logs -f trikorasolns_glpi_init
----
====

=== Deploy the GLPI Web Application container

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-glpi-web.yaml
----

[NOTE]
====
To check the logs of the web container.

[source,bash]
----
podman logs -f trikorasolns_glpi_web
----
====

=== Deploy the cron container

TBD.

== Access the application

=== Web Application

Access the application through the following URL.

http://localhost:9380/

=== GLPI Console

[source,bash]
----
podman exec -it trikorasolns_glpi_glpi /bin/bash
----

== Undeploy the application

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/undeploy-app.yaml
----

== Security scan the image

Using link:[Grype] 

[source,bash]
----
grype localhost/trikorasolns_glpi_core -o json  | jq '.matches.[] | select(.vulnerability.severity == "Critical")' | jq '{id:.vulnerability.id, name:.artifact.name}'
----