= Restore GLPI using Podman
A. Costa <a dot costa at trikorasolutions dot com>
:description: This document describes the steps to restore a GLPI database on a Podman environment.
:icons: font
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

This document describes the steps to import an existing GLPI installation into local Podman POD. It might be used for testing purposes for instance.

== Requirements

* GLPI database export
* GLPI crypt
* GLPI files
* GLPI plugins

[WARNING]
====
Make sure the target environment is clean as the previous GLPI database will 
be imported. Otherwise the import process might fail.
====

=== Collect the GLPI crypt key

The import process needs the `glpicrypt.key` file so it can encrypt/decrypt 
sensitive data. Ths `init` container is prepared to copy this crypt file
to the correct folder. These are the steps required to be performed so the 
`init` container can import this file correctly.

[WARNING]
====
A `The key file "/etc/glpi//glpicrypt.key" used to encrypt/decrypt 
sensitive data is missing.` error might be presented during the `update` 
process. If this occurs it's because this required file is missing in order for the update process to perform correctly.
====

Collect the file from the source GLPI environment. The file might be on 
several locations such as:

* `/var/www/html/glpi/config`
* `/var/www/html/config`
* `/etc/glpi`

The `init` container is prepared to import the contents of this file if the
contents are added into the `GLPI_CRYPT` environment variable under the
following format:

1. tar.gz the file
// 1. encode in base64

When executing the `deploy-glpi-init.yaml` playbook pass this file as
`crypt_file_location` parameter.

== Steps

Create the POD and the MariaDB database.

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/prepare-database.yaml
----

Once the database is started copy the backup mariadb database backup file.

[source,bash]
----
podman cp 2023-08-07-23-00-21.glpi.backup.sql trikorasolns_glpi_db:/tmp/
----

Connect to the MariaDB database container.

[source,bash]
----
podman exec -it trikorasolns_glpi_db /bin/bash
----

Import the database.

[source,bash]
----
mysql -u trikorasolns_glpi -p trikorasolns_glpi < /tmp/2023-08-07-23-00-21.glpi.backup.sql
----

Start the init container so the initialization is executed.

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-glpi-init.yaml -e crypt_file_location=/tmp/glpicrypt.tgz
----

The result should be the something like the following messages, depending on the version.

Deploy the web container.

[source,bash]
----
ansible-playbook src/scripts/deploy/devPodman/deploy-glpi-web.yaml 
----
