= Kind Application Deployment
Angel Casanova; Antonio Costa
:revdate: {docdate}
:toc: left
:icons: font
:description: This section describes how to deploy the project applications on the kind cluster.
:source-highlighter: rouge

This document describes how to manage your king cluster.

== Verify the installation

Run `kind get cluster` if you see `twm` within the output.
You can also run `kubectl cluster-info --context kind-twm`.
Output:

[source,text]
----
Kubernetes control plane is running at https://127.0.0.1:37967
CoreDNS is running at https://127.0.0.1:37967/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
----

== Create the namespace in kubernetes.

Create the twm namespace.

[source,bash]
----
kubectl create namespace twm
----

== Add the local resolution to your host

It is important to add the dns resolutions of the services.
As each of the services, will call other service by its name, it is important to add its entries in the local ressolv.conf.
But, for the moment it is easier to hard-coded them into the hosts file since our deployment is still local.

[source,bash]
----
cat <<EOF >>/etc/hosts
# [START] itwm-kind resolutions
127.0.0.1    twm-registry
127.0.0.1    keycloak.twm.svc.cluster.local
127.0.0.1    itwm-bl.twm.svc.cluster.local
127.0.0.1    itwm-web.twm.svc.cluster.local
127.0.0.1    phpmyadmin.twm.svc.cluster.local
127.0.0.1    grafana.twm.svc.cluster.local
## [END] itwm-kind resolutions
EOF
----

== Keycloak

First build and publish our custom image.
For this check the
link:../keycloak/keycloak-setup.adoc#container-image-creation[Container Image Creation] section of the keyclkoak setup documentation.

.Check details
[%collapsible]
====

[]
======
include::../../technical/keycloak/keycloak-setup.adoc[tag=container-image-creation-bash]

include::../../technical/keycloak/keycloak-setup.adoc[tag=init-container-image-creation-bash]
======

====

.Using Buildah
[]
====

Collect the image ID for the Keycloak dev image.

[source,bash]
----
buildah images --filter reference=trikora_workplace_mgr_dev_keycloak --format="{{.ID}}"
----

Push the image to the local repository.

[source,bash]
----
buildah push $(buildah images --filter reference=trikora_workplace_mgr_dev_keycloak --format="{{.ID}}") \
  docker://localhost:5000/trikora_workplace_mgr_dev_keycloak:20.0.3-$(buildah images --filter reference=trikora_workplace_mgr_dev_keycloak --format="{{.Tag}}")
buildah push $(buildah images --filter reference=trikora_workplace_mgr_dev_keycloak_init --format="{{.ID}}") \
  docker://localhost:5000/trikora_workplace_mgr_dev_keycloak_init:20.0.3-$(buildah images --filter reference=trikora_workplace_mgr_dev_keycloak_init --format="{{.Tag}}")
----

====

See if the image has been pushed correctly:

[source,bash]
----
curl -s http://localhost:5000/v2/_catalog | jq .
curl http://localhost:5000/v2/trikora_workplace_mgr_dev_keycloak/tags/list | jq .
----

.How to move an image to kind, without pushing it
[%collapsible]
======
.Using Kind load
[]
====

Then it is possible (*It is not needed*) to load the image to the kind cluster without pushing it.
You just need to build an image and then pass dump it into the kind cluster with the following command.

[source,bash]
----
kind load docker-image -n twm trikora_workplace_mgr_dev_keycloak:20.0.3
kind load docker-image -n twm trikora_workplace_mgr_dev_keycloak_init:20.0.3
----

====

======

=== Load the yaml's configuration files

[source,bash]
----
kubectl apply -f src/main/kind/keycloak/keycloak/10-configmap.yaml
kubectl apply -f src/main/kind/keycloak/keycloak/15-secret.yaml
kubectl apply -f src/main/kind/keycloak/keycloak/20-deployment.yaml
kubectl apply -f src/main/kind/keycloak/keycloak/31-service-ingress.yaml
kubectl apply -f src/main/kind/keycloak/keycloak/40-ingress.yaml
----

=== Realm Export (You can import in the image with the init container)

[source,bash]
----
kubectl -n twm  exec -it $(kubectl -n twm get pods | grep keycloak | awk '{print $1}') -- /opt/keycloak/bin/kc.sh export --realm trikorasolutions --dir /opt/keycloak/data --users same_file
kubectl cp twm/$(kubectl -n twm get pods | grep keycloak | awk '{print $1}'):/opt/keycloak/data/trikorasolutions-realm.json src/main/resources/META-INF/resources/keycloak/trikorasolutions-realm.json

----

== MariaDB

Deploy the MariaDB database.
In order to do so, we are going to use the link:https://github.com/trikorasolns/helm-charts[trikora helm chart repository].

First template the MariaDB Helm values (Run form itsm root directory).

[source,bash]
----
jinja2 --format=yaml \
  -DDB_PASSWORD=trikora_itsm -DDB_ROOT_PASSWORD=trikora_itsm \
  src/main/kind/helm-charts/helm-mariadb-values.yaml > /tmp/helm-mariadb-values.yaml
----

[WARNING]
====
You need to install jinja2 with `pip install jinja2-cli`
====

Execute the following command.

[WARNING]
====
ATTOW the Helm Charts aren't deployed as such so the
`helm update` command must be executed from the Helm Chart project folder, after downloading the project from link:https://github.com/trikorasolns/helm-charts[trikorasolns/helm-charts]
or a fork.
====

Run the following command from the downloaded `helm-chars` directory:

[source,bash]
----
helm upgrade --install --namespace twm -f /tmp/helm-mariadb-values.yaml mariadb mariadb
----

If you need to uninstall the release, you can always:

[source,bash]
----
helm uninstall -n twm mariadb
----

[NOTE]
====
Remember that it is necessary to uninstall the helm release if you modify the files within the `trikorasolns/helm-charts` repository.
====

== PHP My Admin (optional)

This pod will allow you to manage the database of the application Run form itsm root directory

[source,bash]
----
cp src/main/kind/helm-charts/helm-phpmyadmin-values.yaml /tmp/helm-phpmyadmin-values.yaml
----

Run the following command from the downloaded `helm-chars` directory:

[source,bash]
----
helm upgrade --install --namespace twm -f /tmp/helm-phpmyadmin-values.yaml phpmyadmin phpmyadmin
----

== ITSM BL

See link:./quarkus-deployment.adoc#container-image-creation[how to create an image of the quarkus app] and then, just apply the configuration file:

[IMPORTANT]
====
In order to get the `build/kubernetes/kubernetes.yml` file.
It is needed to (It is important to follow the order in the creation of the images):

1. Build the demo image

2. Build the production image

3. Change the `imagePullPolicy` of the init container from `IfNotPresent` to `Always`.
(This third step may be unnecessary in future version since it comes from a bug in the kubernetes extension)
====

[source,bash]
----
kubectl apply -f src/main/kind/app/10-configmap.yaml
kubectl apply -f src/main/kind/app/15-secret.yaml
kubectl apply -f build/kubernetes/kubernetes.yml
----

[NOTE]
====
The `kubernetes.yml` file, includes the whole quarkus deployment.
Including the security policies (RBAC).
====

== Grafana

Our image use the official granafa image, so it is only necessary to run the .yaml deployment files:

[source,bash]
----
kubectl apply -f src/main/kind/grafana/templates/10-configmap.yaml
kubectl apply -f src/main/kind/grafana/templates/15-secret.yaml
kubectl apply -f src/main/kind/grafana/templates/20-deployment.yaml
kubectl apply -f src/main/kind/grafana/templates/30-service.yaml
sleep 20
./src/main/grafana/load_init_config_kind.sh
----

[IMPORTANT]
====
It is necesary to run the last script, since it load the organization, the datasource and the first dashboard. If not, the user will get an error on the iframe.
====

== Scale a service

You can change the number of replicas with the following command:

[source,bash]
----
kubectl -n twm scale --replicas=1 deployment.apps/bl
----

Even though, in the case of quarkus, you can simply delete the pod and the deployment will restart the whole process for generating a new one.

== Access a service

If you run `kubectl -n twm get all`, then you will see all the architecture:

[source,text]
----
NAME                              READY   STATUS    RESTARTS      AGE
pod/itwm-bl-6b499bc569-85dd9      1/1     Running   0             79m
pod/itwm-web-764d84b7b9-59492     1/1     Running   1 (94m ago)   24h
pod/keycloak-78c9459555-qs4qv     1/1     Running   2 (94m ago)   4d23h
pod/mariadb-0                     1/1     Running   2 (94m ago)   4d21h
pod/phpmyadmin-7c46c96c4f-28wmh   1/1     Running   2 (94m ago)   4d21h

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
service/itwm-bl       NodePort    10.96.170.100   <none>        80:31070/TCP      20h
service/itwm-web      NodePort    10.96.235.249   <none>        80:31020/TCP      4d21h
service/keycloak      ClusterIP   10.96.24.188    <none>        80/TCP,443/TCP    4d23h
service/mariadb       NodePort    10.96.89.53     <none>        3306:31006/TCP    4d21h
service/phpmyadmin    NodePort    10.96.229.33    <none>        80:31079/TCP      4d21h
service/phpmyadmin2   NodePort    10.96.147.158   <none>        30090:30091/TCP   4d21h

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/itwm-bl      1/1     1            1           20h
deployment.apps/itwm-web     1/1     1            1           24h
deployment.apps/keycloak     1/1     1            1           4d23h
deployment.apps/phpmyadmin   1/1     1            1           4d21h

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/itwm-bl-6b499bc569      1         1         1       20h
replicaset.apps/itwm-web-764d84b7b9     1         1         1       24h
replicaset.apps/keycloak-78c9459555     1         1         1       4d23h
replicaset.apps/phpmyadmin-7c46c96c4f   1         1         1       4d21h

NAME                       READY   AGE
statefulset.apps/mariadb   1/1     4d21h

----

So, you can connect to the container with: `http://<service-name>.twm.svc.cluster.local:<port>`.
When port is the right one in the column PORT.

ATTOW keycloak is already configured with the ClusterIP, a load balancer, and a nginx reverse proxy.
So you can simple type http://keycloak.twm.svc.cluster.local/auth/ into your browser and the load balancer will ingress the internet traffic inside the k8s cluster.
This was needed to avoid port mismatches in the issuer of the OIDC auth token.

[NOTE]
====
You should not use localhost instead of the name of the service since the kind cluster is sensible to XSS, CSRF and Same-Origin Policies.
So, in your host browser, you need to access the services by its name, which is <service-name>.twm.svc.cluster.local.
====

=== Getting the cluster IP and the service node.

you can get the cluster IP with the following command:

[source,bash]
----
kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
----

And the service port with the next one:

[source,bash]
----
kubectl -n twm get services/<service-name> -o go-template='{{(index .spec.ports 0).nodePort}}'
----

== Getting a shell to the pod.

As we are using a Deployment kind instead of a Pod, we need to parse a little the pod name.

[source,bash]
----
kubectl exec -it -n twm $(kubectl -n twm get pods | grep <selector> | awk '{print $1}') -- /bin/bash
----

=== Describing a pod

[source,bash]
----
kubectl -n twm describe pod $(kubectl -n twm get pods | grep <selector> | awk '{print $1}')
----

=== Access the logs of the pod

[source,bash]
----
kubectl -n twm logs -f -c init $(kc get pods -n twm | grep <selector> |  awk '{print $1}')
----

=== Useful bash one-liners

1. Check port in different common hostnames.

[source,bash]
----
KC_NODE_PORT=31808 ; for KC_HOST in {'127.0.0.1','localhost','192.168.1.212','keycloak.localdomain'}; do curl "http://${KC_HOST}:${KC_NODE_PORT}" ; done
----

== References

* link:https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster[Interacting with your cluster]
* link:https://medium.com/@nnilesh7756/copy-directories-and-files-to-and-from-kubernetes-container-pod-19612fa74660[Kubernetes copy files]
* link:https://kind.sigs.k8s.io/docs/user/local-registry/[Kind local registry]
* link:https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/[Kind how to load images]
* link:https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/openshift-examples/keycloak.yaml[Old YALM example]
* link:https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/maven-tooling.adoc#remote-development-mode[Run quarkus image on Dev mode]
* link:https://quarkus.io/guides/getting-started-testing#quarkus-test-resource[Quarkus test containers]
* link:https://github.com/quarkusio/quarkus/blob/2.13.0.Final/test-framework/infinispan-client/src/main/java/io/quarkus/test/infinispan/client/InfinispanTestResource.java#L14[Quarkus test containers git example]
* link:https://github.com/lukin0110/docker-gradle/blob/master/Dockerfile[Gradlew dockerfile]
* link:https://www.authelia.com/integration/openid-connect/grafana/[Grafana OIDC]
* link:https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/[Grafana K8s]
* link:https://janikvonrotz.ch/2020/08/27/grafana-oauth-with-keycloak-and-how-to-validate-a-jwt-token/[Grafana Example]
