= Keycloak Configuration
Angel Casanova; Antonio Costa
:revdate: {docdate}
:toc: left
:icons: font
:description: This section describes how to deploy trikora workspace manager into kind.
:source-highlighter: rouge

This document will guide you to make a full localhost deployment of kubernetes in kind.

== Requirements

=== Kubectl Installation

When running `kind.sh` we will get the following error if the kubernetes command-line tool is not installed:

[source,text]
----
ERROR: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Please install kubectl 1.15 or higher
----

The Kubernetes command-line tool, kubectl, allows you to run commands against Kubernetes clusters.
You can use kubectl to deploy applications, inspect and manage cluster resources, and view logs.

How to download kubectl in linux:

[source,bash]
----
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
kubectl version --client
----

How to use it without root(It is not necessary as we have installed it with `-m 0755`):

[source,bash]
----
chmod +x kubectl
mkdir -p ~/.local/bin
mv ./kubectl ~/.local/bin/kubectl
# and then append (or prepend) ~/.local/bin to $PATH
----

=== Helm Installation

When running `kind.sh` we will get the following error if Helm is not installed:

[source,text]
----
ERROR: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Helm could not be found. To get helm: https://helm.sh/docs/intro/install/
ERROR: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
----

How to download helm in linux:

[source,bash]
----
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
chmod 700 get_helm.sh
./get_helm.sh
helm version
----

[NOTE]
====
Helm is include in the fedora repositories up from `Fedora v35.x.x`
====

=== Docker Installation (Optional)

It is a prerequisite to install docker:

[source,bash]
----
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
docker --version
sudo systemctl [start | enable] docker
----

How to use it without root:

[source,bash]
----
sudo groupadd docker
sudo usermod -aG docker $USER
----

[NOTE]
====
You can run the command `newgrp docker` to apply the group changes to the current terminal session.
Then check that after running the `groups` command, you see docker.
====

=== Podman/Buildah: Allow bare http for pushing images

It is possible to run the `kind.sh` script without `Docker` but in order to do so, it is necessary to create the file `/etc/containers/registries.conf.d/kind-registry.conf`, with the following content:

[source,text]
----
[[registry]]
location = "kind-registry.local:5000"
insecure = true
----

This file will allow us to still pushing images with bare http.

== Other Considerations

=== Port Bindings

Port bindings allow connecting the host with the kind cluster:

.Port binding
[%header,cols="1m,3"]
|===
| Port | Description

| 31080
| Keycloak Console

| 31079
| PHP My Admin

| 31070
| Quarkus Console

| 31020
| Angular App

| 31006
| Grafana
|===


[#kind-installation]
== Kind Quick Start

The first step is installing https://kind.sigs.k8s.io/[kind]`.
The easiest way of doing so is using the link:https://github.com/snowdrop/[Snowdrop project's] link:https://github.com/snowdrop/k8s-infra/[k8s-infra]
repository.
It provides scripts and link:https://github.com/snowdrop/k8s-infra/tree/main/kind[instructions]
on how to perform this installation.

=== Container Registry

ATTOW the options to pass to the bash script are the following.

[]
====
[source,bash]

----
install \
  --registry-name "kind-registry.local" \
  --registry-port "5000"
----

====

So the full command to install the container registry would be the following.

[]
====

.Create container registry bash command
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/registry.sh" | \
bash -s install --registry-name "kind-registry.local" --registry-port "5000"
----

====

=== Kind Cluster

ATTOW the options to pass to the bash script are the following.

[source,bash]
----
install \
  --cluster-name twm \
  --port-map '31080:31080,31079:31079,31070:31070,31020:31020,31006:31006' \
  --registry-name "kind-registry.local" \
  --registry-port "5000"
----

[]
====

.Create kind cluster bash command
[source,bash]
----
curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | \
bash -s \
  install \
  --ingress nginx \
  --cluster-name twm \
  --port-map '31080:31080,31079:31079,31070:31070,31020:31020,31006:31006' \
  --registry-name "kind-registry.local" \
  --registry-port "5000"

----

====

=== Other comments (To Be Removed)

This is an auto-guided script that will let you now all the necessary dependencies that you need to run `kind`.
This guide will assume that such script is called `kind.sh` and it is located at link:../../../main/kind/kind/kind.sh[here].

Update the script if needed:

[source,bash]
----
curl -sLO "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh"
mv kind.sh kind.sh
chmod +x ./kind.sh
mv kind.sh ./src/main/kind/kind/
----

So, you can run it with:

[source,bash]
----
./src/main/kind/kind/kind.sh install \
  --ingress nginx \
  --delete-kind-cluster \
  --cluster-name twm \
  --port-map '31080:31080,31079:31079,31070:31070,31020:31020,31006:31006'
----


Help output (if ran without attributes):

[source,text]
----
Usage:
	./deploy.sh command [parameters,...]

Available commands:
	install:				Install the kind cluster
	remove:					Remove the kind cluster

Required parameters:
	--ingress [nginx,kourier]:		Ingress to be deployed. One of nginx,kourier.

Optional parameters:
	-h, --help:				This help message

	--cluster-name <name>			Name of the cluster. Default: kind
	--delete-kind-cluster			Deletes the Kind cluster prior to creating a new one. Default: No
	--knative-version <version>		KNative version to be used. Default: 1.9.0
	--kubernetes-version <version>		Kubernetes version to be install. Default: latest
	--registry-image-version <version>	Version of the registry container to be used. Default: 2.6.2
	--registry-password <password>		Registry user password. Default: snowdrop
	--registry-port <port>			Port to publish the registry. Default: 5000
	--registry-user <user>			Registry user. Default: admin
	--secure-registry			Secure the docker registry. Default: No
	--server-ip <ip-address>		IP address to be used. Default: 127.0.0.1
	--use-existing-cluster			Uses existing kind cluster if it already exists. Default: No
	-v, --verbosity <value>			Logging verbosity (0..9). Default: 1
						A verbosity setting of 0 logs only critical events.

----

==== Kind Installation

When running `kind.sh` we will get the following error if kind is not installed:

[source,text]
----
ERROR: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: kind is not installed
ERROR: Use a package manager (i.e 'brew install kind') or visit the official site https://kind.sigs.k8s.io
----

How to download kind in linux:

[source,bash]
----
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
kind version
----

== Post installation steps

Several tools are required to deploy the applications into kind.
To install the requirements follow these steps.

Install the python requirements, such as Ansible.

[soure,bash]
----
pip install -r src/main/kind/requirements.txt
----

Install other requirements.

[source,bash]
----
ansible-playbook src/main/kind/install-requirements-ansible-playbook.yaml --ask-become-pass

----

== Trouble Shooting

=== Error: rootlessport cannot expose privileged port 80

Command Output: Error: rootlessport cannot expose privileged port 80, you can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024), or choose a larger port number (>= 1024): listen tcp 0.0.0.0:80: bind: permission denied.

=== Cannot connect to the Docker daemon at unix:///var/run/docker.sock

The docker daemon is stopped, just `sudo systemctl start docker`.

== Kind Migration References

* Official Docs:
** link:https://kind.sigs.k8s.io/[What is kind]
** link:https://kind.sigs.k8s.io/docs/user/quick-start/#installation[Kind Quickstart installation]
** link:https://kind.sigs.k8s.io/docs/user/rootless/[Running Kind with Podman Rootless]

* Others:
** link:https://github.com/jacobdotcosta/k8s-infra/tree/merge-kind-scripts/kind[Snowdrop project]
** link:https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[Kubectl Installation]
** link:https://helm.sh/docs/intro/install/[Helm Installation]
** link:https://docs.docker.com/engine/install/ubuntu/[Docker installation]

* Future Work
** link:https://williamlieurance.com/insecure-podman-registry/[Podman v2 config for insecure registries]
