= Build GLPI Container
A. Costa <a dot costa at trikorasolutions dot com>
:description: This document described the steps to build this GLPI image.
:icons: font
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

Instructions to build the GLPI containers.

== Requirements

* link:https://buildah.io/[Buildah]
* link:https://github.com/anchore/grype/blob/main/README.md[Grype]

== Build images

[.lead]
Build the 4 container images that compose the project.

=== Using Ansible

[.lead]
Automated build using Ansible.

[source,bash]
----
ansible-playbook src/scripts/build/build-images.yaml
----

=== Using the command line

[.lead]
Manual build instructions.

Build the GLPI core image.

[source,bash]
----
buildah bud -t trikorasolns_glpi_core -f src/main/core/Dockerfile
----

Build the GLPI init container image.

[source,bash]
----
buildah bud -t trikorasolns_glpi_init -f src/main/init/Dockerfile
----

Build the GLPI image for the Web Application.

[source,bash]
----
buildah bud -t trikorasolns_glpi_web -f src/main/web/Dockerfile
----

TODO: Build the GLPI image for the Cron Application.

[source,bash]
----
buildah bud -t trikorasolns_glpi_cron -f src/main/cron/Dockerfile
----

== Security scan the image

Execute a security scan on the generated images.

Using link:https://github.com/anchore/grype[Grype], execute the following 
 command to show Critical CVE and the associated artifact name.

[source,bash]
----
grype localhost/trikorasolns_glpi_core -o json  | jq '.matches.[] | select(.vulnerability.severity == "Critical")' | jq '{id:.vulnerability.id, name:.artifact.name}'
----

The scan will show the Critical CVE.

[source,json]
----
{
  "id": "CVE-2023-45853",
  "name": "zlib1g-dev"
}
----

To list a table with all CVE simply execute the grype command without other options than the image name.

[source,bash]
----
grype localhost/trikorasolns_glpi_core
----

[source,]
----
 ✔ Loaded image                                                                                                                localhost/trikorasolns_glpi_core:latest 
 ✔ Parsed image                                                                                sha256:3a408d87880550b6bf2fff0892caf0d218c57cc8064886aa69c8fde28071e15f 
 ✔ Cataloged contents                                                                                 38010a6b246df5971dd52041a76a8dfcc2feb80a71ef6e8c93d281d8081e3b1c 
   ├── ✔ Packages                        [278 packages]  
   ├── ✔ File digests                    [8,800 files]  
   ├── ✔ File metadata                   [8,800 locations]  
   └── ✔ Executables                     [1,071 executables]  
 ✔ Scanned for vulnerabilities     [375 vulnerability matches]  
   ├── by severity: 2 critical, 92 high, 261 medium, 11 low, 386 negligible (131 unknown)
   └── by status:   0 fixed, 883 not-fixed, 508 ignored (1 dropped)
NAME                       INSTALLED                FIXED-IN     TYPE  VULNERABILITY     SEVERITY
...
passwd                     1:4.13+dfsg1-1+b1        (won't fix)  deb   CVE-2023-4641     Medium      
passwd                     1:4.13+dfsg1-1+b1        (won't fix)  deb   CVE-2023-29383    Low         
passwd                     1:4.13+dfsg1-1+b1        (won't fix)  deb   CVE-2024-56433    Low         
passwd                     1:4.13+dfsg1-1+b1                     deb   CVE-2007-5686     Negligible  
patch                      2.7.6-7                               deb   CVE-2010-4651     Negligible  
patch                      2.7.6-7                               deb   CVE-2018-6951     Negligible  
patch                      2.7.6-7                               deb   CVE-2018-6952     Negligible  
patch                      2.7.6-7                               deb   CVE-2021-45261    Negligible  
perl                       5.36.0-7+deb12u1         (won't fix)  deb   CVE-2023-31484    High        
perl                       5.36.0-7+deb12u1                      deb   CVE-2011-4116     Negligible  
perl                       5.36.0-7+deb12u1                      deb   CVE-2023-31486    Negligible  
perl-base                  5.36.0-7+deb12u1         (won't fix)  deb   CVE-2023-31484    High        
perl-base                  5.36.0-7+deb12u1                      deb   CVE-2011-4116     Negligible  
perl-base                  5.36.0-7+deb12u1                      deb   CVE-2023-31486    Negligible  
perl-modules-5.36          5.36.0-7+deb12u1         (won't fix)  deb   CVE-2023-31484    High        
perl-modules-5.36          5.36.0-7+deb12u1                      deb   CVE-2011-4116     Negligible  
perl-modules-5.36          5.36.0-7+deb12u1                      deb   CVE-2023-31486    Negligible  
procps                     2:4.0.2-3                (won't fix)  deb   CVE-2023-4016     Low         
re2c                       3.0-2                                 deb   CVE-2018-21232    Negligible  
tar                        1.34+dfsg-1.2+deb12u1                 deb   CVE-2005-2541     Negligible  
util-linux                 2.38.1-5+deb12u3                      deb   CVE-2022-0563     Negligible  
util-linux-extra           2.38.1-5+deb12u3                      deb   CVE-2022-0563     Negligible  
zlib1g-dev                 1:1.2.13.dfsg-1          (won't fix)  deb   CVE-2023-45853    Critical
----
